### ISSUE TITLE
When downloading mupit_modbase.sql.gz (Network is unreachable)

### ISSUE THREAD

**Issue by JIAJZHAN-Kairos** [bbglab/intogen-plus#34]
```
wget http://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz -O /g/data/gx8/projects/Jiajun_intogen/intogen-plus-2023/datasets/hotmaps/mupit_database.db.mysql.gz
--2024-07-28 05:20:19--  http://karchinlab.org/data/HotMAPS/mupit_modbase.sql.gz
Resolving karchinlab.org (karchinlab.org)... 162.129.223.26
Connecting to karchinlab.org (karchinlab.org)|162.129.223.26|:80... failed: Network is unreachable.
make: *** [datasets/hotmaps/hotmaps.mk:15: /g/data/gx8/projects/Jiajun_intogen/intogen-plus-2023/datasets/hotmaps/mupit_database.db] Error 4
```
I was trying to download manually, but 404.

**Comment by skanwal** [comment]
This was also reported to HoTMaps https://github.com/KarchinLab/HotMAPS/issues/1 but no comments have been made since March.

**Comment by FedericaBrando** [comment]
Hi all,

Thanks for letting us know about the installation issue with HotMAPS database. Our team is already working on a solution to implement it in the next release, that will happen soon. Thanks for your patient

Bests,

Federica

**Comment by skanwal** [comment]
Hi @FedericaBrando ,

Thanks for the response. Can we please get the ETA for the next release? This will greatly help us plan analysis for our project.

**Comment by JIAJZHAN-Kairos** [comment]
> Hi all,
> 
> 
> 
> Thanks for letting us know about the installation issue with HotMAPS database. Our team is already working on a solution to implement it in the next release, that will happen soon. Thanks for your patient
> 
> 
> 
> Bests,
> 
> 
> 
> Federica

Hi Federica,

Thank you for the update and for your team’s efforts in resolving the issue. We appreciate your quick action on this matter. Could you please let us know the expected timeframe for the next release?

**Comment by FedericaBrando** [comment]
It will be released this fall, thanks for your patience!

**Comment by RyulKim-Inocras** [comment]
Hi Federica,

When do you expect this issue to be solved?

**Comment by JIAJZHAN-Kairos** [comment]
For those who are looking for the mupit_modbase.sql.gz file needed for the HotMAPS dataset processing, you can download it from the following link:

[Download mupit_modbase.sql.gz](https://www.dropbox.com/scl/fi/2fvqta3mcpy0jjs8ta3fc/mupit_modbase.sql.gz?rlkey=z2ud0kaqyr1p23kryuxv9o168&st=21vhlb4f&dl=1)

This should help bypass the issue of the missing file when running the pipeline.

**Comment by RyulKim-Inocras** [comment]
Thanks a lot!!!

I need to download one more thing

*http://karchinlab.org/data/HotMAPS/pdb_info.txt.gz
<http://karchinlab.org/data/HotMAPS/pdb_info.txt.gz>*

which don't exist anymore.

Could please send me the file too?

Best regards,

Ryul Kim


2024년 11월 4일 (월) 오전 11:24, JIAJZHAN-Kairos ***@***.***>님이 작성:

**Comment by RyulKim-Inocras** [comment]
Thanks a lot!!!

I need to download one more thing

http://karchinlab.org/data/HotMAPS/pdb_info.txt.gz

which don't exist anymore. 

Could please send me the file too?

**Comment by JIAJZHAN-Kairos** [comment]
> Thanks a lot!!!
> 
> I need to download one more thing
> 
> http://karchinlab.org/data/HotMAPS/pdb_info.txt.gz
> 
> which don't exist anymore.
> 
> Could please send me the file too?

Regarding `pdb_info.txt.gz` you can change the address to [this link](https://www.dropbox.com/scl/fi/0lklxk9h8fkzzwrz9ge1x/pdb_info.txt.gz?rlkey=uadoiylkv1pcuaed267q751eu&st=n1ds6yhq&dl=1) for downloading.

In `build/hotsmap/biounit.sh`, you may need to edit this line: `rsync -rlpt -v -z --delete --port=33444 rsync.rcsb.org::ftp_data/`...... 

Additionally, in `others.mk`, the link for downloading [genes.csv](https://genome.weizmann.ac.il/horde/app/webroot/index.php/download/genes.csv) should be updated.

These are the link issues I encountered and how I resolved them. While I am not certain that these files are identical to the ones used by the author, they seem to be working well for now.

For your reference.

**Comment by FedericaBrando** [comment]
This has been added in 
- #52
