### ISSUE TITLE
FTP download from RCSB PDB is deprecated

### ISSUE THREAD

**Issue by Joannavonberg** [bbglab/intogen-plus#43]
See: https://www.rcsb.org/news/636151b266d6046810db7f0f 
From 1st of November 2024, FTP download from the Protein Databank is not possible anymore. There's an rsync server, I'm currently trying to edit the biounit.sh script to fix this.

**Comment by Joannavonberg** [comment]
I'm trying to setup git on the VM I'm using to build Intogen and haven't gotten it to work yet (wanted to push my edits to this repo so I could do a pull request). I have to go into a meeting now, but it seems like this works: change line 9 in biounit.sh (https://github.com/bbglab/intogen-plus/blame/master/build/datasets/hotmaps/biounit.sh#L9) to "rsync -rptz --copy-links --port=33444 rsync.wwpdb.org::ftp_data/biounit/coordinates/all/*.pdb1.gz ${tmpdir}/"

**Comment by FedericaBrando** [comment]
Hi Joanna, thanks a lot for this! I would be happy to review the PR - if you are encountering problems with setting up git I will edit this myself. No problem! :)

**Comment by Joannavonberg** [comment]
I think I did it! I never made a pull request for a repo I didn't have write access to, so didn't realize I had to fork your repo
