### ISSUE TITLE
Where can I find dictionary_long_name.json file?

### ISSUE THREAD

**Issue by RyulKim-Inocras** [bbglab/intogen-plus#45]
You recommended to use CANCER abbreviations defined in dictionary_long_name.json file. 
But I can't find the file. 

Could you please provide the full path to the dictionary_long_name.json? 

Sincerely, 

Ryul Kim

**Comment by FedericaBrando** [comment]
Hi @RyulKim-Inocras, This file will be in the datasets/oncotree folder that is generated in the building process, if you want to take a look before building the dataset, you can see it here: [dictionary_long_names.json](https://github.com/bbglab/intogen-plus/blob/master/build/datasets/oncotree/dictionary_long_names.json)

**Comment by RyulKim-Inocras** [comment]
Thank! I found it!
